-- =====================================================================================================
-- R__audit__action_types · Catálogo de acciones de la auditoría (Fase 10, D10-01). Se genera junto con
-- src/Modules/Audit/Pos.Modules.Audit.Contracts/AuditActions.cs: una prueba compara ambos.
-- Las acciones que ya no estén en el código no se borran (las filas selladas las siguen usando).
-- =====================================================================================================

INSERT INTO audit.action_types (code, module, name, default_severity) VALUES
    ('AUDIT_VERIFICATION_FAILED', 'audit', 'Bitácora alterada: verificación con hallazgos', 'CRITICAL'),
    ('AUDIT_VERIFIED', 'audit', 'Bitácora verificada sin hallazgos', 'INFO'),
    ('INTEGRITY_CERTIFICATE_ISSUED', 'audit', 'Constancia de integridad emitida', 'INFO'),
    ('INTEGRITY_INCIDENT_ACKNOWLEDGED', 'audit', 'Incidente de integridad reconocido', 'WARNING'),
    ('BACKUP_COMPLETED', 'backup', 'Backup realizado y verificado', 'INFO'),
    ('BACKUP_DESTINATION_CHANGED', 'backup', 'Destino de backups creado o modificado', 'WARNING'),
    ('BACKUP_DOWNLOADED', 'backup', 'Backup descargado', 'WARNING'),
    ('BACKUP_FAILED', 'backup', 'Backup fallido', 'CRITICAL'),
    ('BACKUP_RESTORED', 'backup', 'Backup restaurado', 'CRITICAL'),
    ('RECOVERY_CODE_CONFIRMED', 'backup', 'Código de recuperación confirmado', 'INFO'),
    ('RECOVERY_CODE_GENERATED', 'backup', 'Código de recuperación generado', 'WARNING'),
    ('RESTORE_TEST_FAILED', 'backup', 'Restauración de prueba fallida', 'CRITICAL'),
    ('RESTORE_TEST_PASSED', 'backup', 'Restauración de prueba correcta', 'INFO'),
    ('CASH_CORRECTION', 'cash', 'Corrección de caja', 'WARNING'),
    ('CASH_DRAWER_OPENED_NO_SALE', 'cash', 'Cajón abierto sin venta', 'WARNING'),
    ('CASH_SESSION_CLOSED', 'cash', 'Jornada de caja cerrada', 'INFO'),
    ('CASH_SESSION_CLOSED_BY_SUPERVISOR', 'cash', 'Jornada cerrada por un supervisor', 'WARNING'),
    ('CASH_SESSION_CREATED', 'cash', 'Jornada de caja · creado', 'INFO'),
    ('CASH_SESSION_DELETED', 'cash', 'Jornada de caja · eliminado', 'WARNING'),
    ('CASH_SESSION_OPENED', 'cash', 'Jornada de caja abierta', 'INFO'),
    ('CASH_SESSION_REVIEWED', 'cash', 'Cierre de caja revisado', 'INFO'),
    ('CASH_SESSION_UPDATED', 'cash', 'Jornada de caja · modificado', 'INFO'),
    ('CASH_WITHDRAWAL', 'cash', 'Retiro de caja', 'WARNING'),
    ('DENOMINATION_CREATED', 'cash', 'Denominación · creado', 'INFO'),
    ('DENOMINATION_DELETED', 'cash', 'Denominación · eliminado', 'WARNING'),
    ('DENOMINATION_UPDATED', 'cash', 'Denominación · modificado', 'INFO'),
    ('PAYMENT_METHOD_CREATED', 'cash', 'Medio de pago · creado', 'INFO'),
    ('PAYMENT_METHOD_DELETED', 'cash', 'Medio de pago · eliminado', 'WARNING'),
    ('PAYMENT_METHOD_UPDATED', 'cash', 'Medio de pago · modificado', 'INFO'),
    ('BRAND_CREATED', 'catalog', 'Marca · creado', 'INFO'),
    ('BRAND_DELETED', 'catalog', 'Marca · eliminado', 'WARNING'),
    ('BRAND_UPDATED', 'catalog', 'Marca · modificado', 'INFO'),
    ('CATALOG_IMPORT_APPLIED', 'catalog', 'Importación de catálogo aplicada', 'INFO'),
    ('CATEGORY_CREATED', 'catalog', 'Categoría · creado', 'INFO'),
    ('CATEGORY_DELETED', 'catalog', 'Categoría · eliminado', 'WARNING'),
    ('CATEGORY_UPDATED', 'catalog', 'Categoría · modificado', 'INFO'),
    ('PRICE_LIST_CREATED', 'catalog', 'Lista de precio · creado', 'INFO'),
    ('PRICE_LIST_DELETED', 'catalog', 'Lista de precio · eliminado', 'WARNING'),
    ('PRICE_LIST_UPDATED', 'catalog', 'Lista de precio · modificado', 'INFO'),
    ('PRODUCT_BARCODE_CREATED', 'catalog', 'Código de barras · creado', 'INFO'),
    ('PRODUCT_BARCODE_DELETED', 'catalog', 'Código de barras · eliminado', 'WARNING'),
    ('PRODUCT_BARCODE_UPDATED', 'catalog', 'Código de barras · modificado', 'INFO'),
    ('PRODUCT_CREATED', 'catalog', 'Producto · creado', 'INFO'),
    ('PRODUCT_DELETED', 'catalog', 'Producto · eliminado', 'WARNING'),
    ('PRODUCT_PACKAGING_CREATED', 'catalog', 'Presentación · creado', 'INFO'),
    ('PRODUCT_PACKAGING_DELETED', 'catalog', 'Presentación · eliminado', 'WARNING'),
    ('PRODUCT_PACKAGING_UPDATED', 'catalog', 'Presentación · modificado', 'INFO'),
    ('PRODUCT_PRICE_CHANGED', 'catalog', 'Precio de venta cambiado', 'INFO'),
    ('PRODUCT_PRICE_CREATED', 'catalog', 'Precio de producto · creado', 'INFO'),
    ('PRODUCT_PRICE_DELETED', 'catalog', 'Precio de producto · eliminado', 'WARNING'),
    ('PRODUCT_PRICE_SCHEDULED', 'catalog', 'Precio de venta programado', 'INFO'),
    ('PRODUCT_PRICE_UPDATED', 'catalog', 'Precio de producto · modificado', 'INFO'),
    ('PRODUCT_TAX_CREATED', 'catalog', 'Impuesto de producto · creado', 'INFO'),
    ('PRODUCT_TAX_DELETED', 'catalog', 'Impuesto de producto · eliminado', 'WARNING'),
    ('PRODUCT_TAX_UPDATED', 'catalog', 'Impuesto de producto · modificado', 'INFO'),
    ('PRODUCT_UPDATED', 'catalog', 'Producto · modificado', 'INFO'),
    ('TAX_CREATED', 'catalog', 'Impuesto · creado', 'INFO'),
    ('TAX_DELETED', 'catalog', 'Impuesto · eliminado', 'WARNING'),
    ('TAX_RATE_CREATED', 'catalog', 'Tarifa de impuesto · creado', 'INFO'),
    ('TAX_RATE_DELETED', 'catalog', 'Tarifa de impuesto · eliminado', 'WARNING'),
    ('TAX_RATE_UPDATED', 'catalog', 'Tarifa de impuesto · modificado', 'INFO'),
    ('TAX_UPDATED', 'catalog', 'Impuesto · modificado', 'INFO'),
    ('VARIABLE_BARCODE_RULE_CREATED', 'catalog', 'Regla de código de báscula · creado', 'INFO'),
    ('VARIABLE_BARCODE_RULE_DELETED', 'catalog', 'Regla de código de báscula · eliminado', 'WARNING'),
    ('VARIABLE_BARCODE_RULE_UPDATED', 'catalog', 'Regla de código de báscula · modificado', 'INFO'),
    ('CUSTOMER_ANONYMIZED', 'customers', 'Datos del cliente suprimidos', 'WARNING'),
    ('CUSTOMER_CREATED', 'customers', 'Cliente · creado', 'INFO'),
    ('CUSTOMER_DATA_CORRECTED', 'customers', 'Datos del cliente corregidos', 'INFO'),
    ('CUSTOMER_DATA_EXPORTED', 'customers', 'Datos del cliente exportados', 'WARNING'),
    ('CUSTOMER_DELETED', 'customers', 'Cliente · eliminado', 'WARNING'),
    ('CUSTOMER_GROUP_CREATED', 'customers', 'Grupo de clientes · creado', 'INFO'),
    ('CUSTOMER_GROUP_DELETED', 'customers', 'Grupo de clientes · eliminado', 'WARNING'),
    ('CUSTOMER_GROUP_UPDATED', 'customers', 'Grupo de clientes · modificado', 'INFO'),
    ('CUSTOMER_PRICING_ASSIGNED', 'customers', 'Grupo y lista de precio del cliente asignados', 'INFO'),
    ('CUSTOMER_QUICK_CREATED', 'customers', 'Cliente creado en la caja', 'INFO'),
    ('CUSTOMER_UPDATED', 'customers', 'Cliente · modificado', 'INFO'),
    ('DATA_REQUEST_CREATED', 'customers', 'Solicitud de titular · creado', 'INFO'),
    ('DATA_REQUEST_DELETED', 'customers', 'Solicitud de titular · eliminado', 'WARNING'),
    ('DATA_REQUEST_RECEIVED', 'customers', 'Solicitud de un titular recibida', 'INFO'),
    ('DATA_REQUEST_UPDATED', 'customers', 'Solicitud de titular · modificado', 'INFO'),
    ('PRIVACY_POLICY_CREATED', 'customers', 'Política de datos · creado', 'INFO'),
    ('PRIVACY_POLICY_DELETED', 'customers', 'Política de datos · eliminado', 'WARNING'),
    ('PRIVACY_POLICY_UPDATED', 'customers', 'Política de datos · modificado', 'INFO'),
    ('EXPENSE_CATEGORY_CREATED', 'expenses', 'Categoría de gasto · creado', 'INFO'),
    ('EXPENSE_CATEGORY_DELETED', 'expenses', 'Categoría de gasto · eliminado', 'WARNING'),
    ('EXPENSE_CATEGORY_UPDATED', 'expenses', 'Categoría de gasto · modificado', 'INFO'),
    ('EXPENSE_CREATED', 'expenses', 'Gasto · creado', 'INFO'),
    ('EXPENSE_DELETED', 'expenses', 'Gasto · eliminado', 'WARNING'),
    ('EXPENSE_POSTED', 'expenses', 'Gasto registrado', 'INFO'),
    ('EXPENSE_UPDATED', 'expenses', 'Gasto · modificado', 'INFO'),
    ('EXPENSE_VOIDED', 'expenses', 'Gasto anulado', 'WARNING'),
    ('EMPLOYEE_CREATED', 'identity', 'Empleado · creado', 'INFO'),
    ('EMPLOYEE_DELETED', 'identity', 'Empleado · eliminado', 'WARNING'),
    ('EMPLOYEE_UPDATED', 'identity', 'Empleado · modificado', 'INFO'),
    ('LOGIN_FAILED', 'identity', 'Ingreso fallido', 'INFO'),
    ('LOGIN_SUCCEEDED', 'identity', 'Ingreso al sistema', 'INFO'),
    ('LOGOUT', 'identity', 'Salida del sistema', 'INFO'),
    ('OWNER_CREATED', 'identity', 'Propietario creado', 'WARNING'),
    ('OWNER_EMERGENCY_RESET', 'identity', 'Recuperación de emergencia del propietario', 'CRITICAL'),
    ('PASSWORD_CHANGED', 'identity', 'Contraseña cambiada', 'INFO'),
    ('PASSWORD_RESET', 'identity', 'Contraseña restablecida por un administrador', 'WARNING'),
    ('PIN_CHANGED', 'identity', 'PIN cambiado', 'INFO'),
    ('PIN_RESET', 'identity', 'PIN restablecido por un administrador', 'WARNING'),
    ('ROLE_CREATED', 'identity', 'Rol · creado', 'INFO'),
    ('ROLE_DELETED', 'identity', 'Rol · eliminado', 'WARNING'),
    ('ROLE_UPDATED', 'identity', 'Rol · modificado', 'INFO'),
    ('SESSION_REVOKED', 'identity', 'Sesión cerrada por un administrador', 'WARNING'),
    ('SUPERVISOR_AUTHORIZATION_GRANTED', 'identity', 'Autorización de supervisor', 'INFO'),
    ('SYSTEM_ROLE_UPDATED', 'identity', 'Rol de sistema actualizado', 'INFO'),
    ('USER_CREATED', 'identity', 'Usuario · creado', 'INFO'),
    ('USER_DELETED', 'identity', 'Usuario · eliminado', 'WARNING'),
    ('USER_LOCKED', 'identity', 'Usuario bloqueado por intentos fallidos', 'WARNING'),
    ('USER_SESSIONS_REVOKED', 'identity', 'Sesiones del usuario cerradas', 'WARNING'),
    ('USER_UPDATED', 'identity', 'Usuario · modificado', 'INFO'),
    ('ADJUSTMENT_REASON_CREATED', 'inventory', 'Motivo de ajuste · creado', 'INFO'),
    ('ADJUSTMENT_REASON_DELETED', 'inventory', 'Motivo de ajuste · eliminado', 'WARNING'),
    ('ADJUSTMENT_REASON_UPDATED', 'inventory', 'Motivo de ajuste · modificado', 'INFO'),
    ('INVENTORY_ADJUSTMENT_CREATED', 'inventory', 'Ajuste de inventario · creado', 'INFO'),
    ('INVENTORY_ADJUSTMENT_DELETED', 'inventory', 'Ajuste de inventario · eliminado', 'WARNING'),
    ('INVENTORY_ADJUSTMENT_POSTED', 'inventory', 'Ajuste de inventario contabilizado', 'INFO'),
    ('INVENTORY_ADJUSTMENT_UPDATED', 'inventory', 'Ajuste de inventario · modificado', 'INFO'),
    ('INVENTORY_COUNT_CREATED', 'inventory', 'Conteo de inventario · creado', 'INFO'),
    ('INVENTORY_COUNT_DELETED', 'inventory', 'Conteo de inventario · eliminado', 'WARNING'),
    ('INVENTORY_COUNT_POSTED', 'inventory', 'Conteo de inventario contabilizado', 'INFO'),
    ('INVENTORY_COUNT_UPDATED', 'inventory', 'Conteo de inventario · modificado', 'INFO'),
    ('INVENTORY_QUICK_ADJUSTMENT', 'inventory', 'Ajuste rápido desde la caja', 'WARNING'),
    ('INVENTORY_TRANSFER_SHORTAGE', 'inventory', 'Faltante en un traslado', 'WARNING'),
    ('STOCK_BALANCE_REBUILT', 'inventory', 'Saldo reconstruido desde el kardex', 'CRITICAL'),
    ('STOCK_POLICY_CREATED', 'inventory', 'Mínimo y máximo · creado', 'INFO'),
    ('STOCK_POLICY_DELETED', 'inventory', 'Mínimo y máximo · eliminado', 'WARNING'),
    ('STOCK_POLICY_UPDATED', 'inventory', 'Mínimo y máximo · modificado', 'INFO'),
    ('STOCK_TRANSFER_CREATED', 'inventory', 'Traslado · creado', 'INFO'),
    ('STOCK_TRANSFER_DELETED', 'inventory', 'Traslado · eliminado', 'WARNING'),
    ('STOCK_TRANSFER_UPDATED', 'inventory', 'Traslado · modificado', 'INFO'),
    ('STOCK_VERIFICATION_FAILED', 'inventory', 'Verificación del kardex con diferencias', 'CRITICAL'),
    ('LICENSE_ACTIVATED', 'licensing', 'Licencia activada', 'INFO'),
    ('LICENSE_CHECKIN_FAILED', 'licensing', 'Verificación de la licencia fallida', 'WARNING'),
    ('LICENSE_CLOCK_ROLLBACK', 'licensing', 'Reloj atrasado: licencia restringida', 'CRITICAL'),
    ('LICENSE_DEACTIVATED', 'licensing', 'Equipo liberado de la licencia', 'WARNING'),
    ('LICENSE_STATE_CHANGED', 'licensing', 'Cambio de estado de la licencia', 'WARNING'),
    ('BRANCH_CREATED', 'organization', 'Sucursal · creado', 'INFO'),
    ('BRANCH_DELETED', 'organization', 'Sucursal · eliminado', 'WARNING'),
    ('BRANCH_UPDATED', 'organization', 'Sucursal · modificado', 'INFO'),
    ('COMPANY_CREATED', 'organization', 'Empresa · creado', 'INFO'),
    ('COMPANY_DELETED', 'organization', 'Empresa · eliminado', 'WARNING'),
    ('COMPANY_UPDATED', 'organization', 'Empresa · modificado', 'INFO'),
    ('DEVICE_CREATED', 'organization', 'Equipo · creado', 'INFO'),
    ('DEVICE_DELETED', 'organization', 'Equipo · eliminado', 'WARNING'),
    ('DEVICE_PAIRING_CODE_CREATED', 'organization', 'Código de emparejamiento creado', 'INFO'),
    ('DEVICE_PAIRING_FAILED', 'organization', 'Emparejamiento de equipo fallido', 'WARNING'),
    ('DEVICE_UPDATED', 'organization', 'Equipo · modificado', 'INFO'),
    ('NODE_CREATED', 'organization', 'Nodo · creado', 'INFO'),
    ('NODE_DELETED', 'organization', 'Nodo · eliminado', 'WARNING'),
    ('NODE_UPDATED', 'organization', 'Nodo · modificado', 'INFO'),
    ('POS_TERMINAL_CREATED', 'organization', 'Caja · creado', 'INFO'),
    ('POS_TERMINAL_DELETED', 'organization', 'Caja · eliminado', 'WARNING'),
    ('POS_TERMINAL_UPDATED', 'organization', 'Caja · modificado', 'INFO'),
    ('SETUP_COMPLETED', 'organization', 'Configuración inicial completada', 'WARNING'),
    ('TERMINAL_DEVICE_CREATED', 'organization', 'Periférico de caja · creado', 'INFO'),
    ('TERMINAL_DEVICE_DELETED', 'organization', 'Periférico de caja · eliminado', 'WARNING'),
    ('TERMINAL_DEVICE_UPDATED', 'organization', 'Periférico de caja · modificado', 'INFO'),
    ('WAREHOUSE_CREATED', 'organization', 'Bodega · creado', 'INFO'),
    ('WAREHOUSE_DELETED', 'organization', 'Bodega · eliminado', 'WARNING'),
    ('WAREHOUSE_UPDATED', 'organization', 'Bodega · modificado', 'INFO'),
    ('PARTY_CREATED', 'parties', 'Tercero · creado', 'INFO'),
    ('PARTY_DELETED', 'parties', 'Tercero · eliminado', 'WARNING'),
    ('PARTY_UPDATED', 'parties', 'Tercero · modificado', 'INFO'),
    ('PROMOTION_CREATED', 'promotions', 'Promoción · creado', 'INFO'),
    ('PROMOTION_DELETED', 'promotions', 'Promoción · eliminado', 'WARNING'),
    ('PROMOTION_UPDATED', 'promotions', 'Promoción · modificado', 'INFO'),
    ('ACCOUNT_PAYABLE_CREATED', 'purchasing', 'Cuenta por pagar · creado', 'INFO'),
    ('ACCOUNT_PAYABLE_DELETED', 'purchasing', 'Cuenta por pagar · eliminado', 'WARNING'),
    ('ACCOUNT_PAYABLE_UPDATED', 'purchasing', 'Cuenta por pagar · modificado', 'INFO'),
    ('PAYABLE_PAYMENT_CREATED', 'purchasing', 'Pago a proveedor · creado', 'INFO'),
    ('PAYABLE_PAYMENT_DELETED', 'purchasing', 'Pago a proveedor · eliminado', 'WARNING'),
    ('PAYABLE_PAYMENT_POSTED', 'purchasing', 'Pago a proveedor registrado', 'INFO'),
    ('PAYABLE_PAYMENT_UPDATED', 'purchasing', 'Pago a proveedor · modificado', 'INFO'),
    ('PAYABLE_PAYMENT_VOIDED', 'purchasing', 'Pago a proveedor anulado', 'WARNING'),
    ('PURCHASE_CREATED', 'purchasing', 'Compra · creado', 'INFO'),
    ('PURCHASE_DELETED', 'purchasing', 'Compra · eliminado', 'WARNING'),
    ('PURCHASE_ORDER_CREATED', 'purchasing', 'Orden de compra · creado', 'INFO'),
    ('PURCHASE_ORDER_DELETED', 'purchasing', 'Orden de compra · eliminado', 'WARNING'),
    ('PURCHASE_ORDER_UPDATED', 'purchasing', 'Orden de compra · modificado', 'INFO'),
    ('PURCHASE_POSTED', 'purchasing', 'Compra contabilizada', 'INFO'),
    ('PURCHASE_UPDATED', 'purchasing', 'Compra · modificado', 'INFO'),
    ('PURCHASE_VOIDED', 'purchasing', 'Compra anulada', 'WARNING'),
    ('SUPPLIER_BANK_ACCOUNT_CHANGED', 'purchasing', 'Cuenta bancaria de proveedor modificada', 'WARNING'),
    ('SUPPLIER_BANK_ACCOUNT_CREATED', 'purchasing', 'Cuenta bancaria de proveedor registrada', 'INFO'),
    ('SUPPLIER_BANK_ACCOUNT_VERIFIED', 'purchasing', 'Cuenta bancaria de proveedor verificada', 'INFO'),
    ('SUPPLIER_CREATED', 'purchasing', 'Proveedor · creado', 'INFO'),
    ('SUPPLIER_DELETED', 'purchasing', 'Proveedor · eliminado', 'WARNING'),
    ('SUPPLIER_PRODUCT_CREATED', 'purchasing', 'Producto del proveedor · creado', 'INFO'),
    ('SUPPLIER_PRODUCT_DELETED', 'purchasing', 'Producto del proveedor · eliminado', 'WARNING'),
    ('SUPPLIER_PRODUCT_UPDATED', 'purchasing', 'Producto del proveedor · modificado', 'INFO'),
    ('SUPPLIER_RETURN_CREATED', 'purchasing', 'Devolución a proveedor · creado', 'INFO'),
    ('SUPPLIER_RETURN_DELETED', 'purchasing', 'Devolución a proveedor · eliminado', 'WARNING'),
    ('SUPPLIER_RETURN_POSTED', 'purchasing', 'Devolución a proveedor contabilizada', 'INFO'),
    ('SUPPLIER_RETURN_UPDATED', 'purchasing', 'Devolución a proveedor · modificado', 'INFO'),
    ('SUPPLIER_SCHEDULE_CREATED', 'purchasing', 'Días de visita del proveedor · creado', 'INFO'),
    ('SUPPLIER_SCHEDULE_DELETED', 'purchasing', 'Días de visita del proveedor · eliminado', 'WARNING'),
    ('SUPPLIER_SCHEDULE_UPDATED', 'purchasing', 'Días de visita del proveedor · modificado', 'INFO'),
    ('SUPPLIER_UPDATED', 'purchasing', 'Proveedor · modificado', 'INFO'),
    ('SUPPLIER_WITHHOLDING_DEFAULT_CREATED', 'purchasing', 'Retención por defecto del proveedor · creado', 'INFO'),
    ('SUPPLIER_WITHHOLDING_DEFAULT_DELETED', 'purchasing', 'Retención por defecto del proveedor · eliminado', 'WARNING'),
    ('SUPPLIER_WITHHOLDING_DEFAULT_UPDATED', 'purchasing', 'Retención por defecto del proveedor · modificado', 'INFO'),
    ('REPORT_EXPORTED', 'reporting', 'Reporte exportado', 'INFO'),
    ('EXCHANGE_STARTED', 'sales', 'Cambio de mercancía iniciado', 'INFO'),
    ('SALE_CANCELLED', 'sales', 'Venta cancelada', 'WARNING'),
    ('SALE_DISCOUNT_APPLIED', 'sales', 'Descuento manual aplicado', 'INFO'),
    ('SALE_EXPIRED_LOT_AUTHORIZED', 'sales', 'Venta de lote vencido autorizada', 'WARNING'),
    ('SALE_LINE_VOIDED', 'sales', 'Línea eliminada de una venta', 'INFO'),
    ('SALE_PRICE_OVERRIDDEN', 'sales', 'Precio cambiado en la caja', 'WARNING'),
    ('SALE_REPRINTED', 'sales', 'Tiquete reimpreso', 'INFO'),
    ('SALE_VOIDED', 'sales', 'Venta anulada', 'WARNING'),
    ('WARRANTY_REFUND', 'sales', 'Reintegro de dinero por garantía', 'WARNING'),
    ('SETTING_CHANGED', 'settings', 'Configuración modificada', 'INFO'),
    ('SETTING_OVERRIDE_REMOVED', 'settings', 'Excepción de configuración eliminada', 'INFO'),
    ('CLOCK_JUMP_DETECTED', 'system', 'Reloj del servidor atrasado respecto a la bitácora', 'CRITICAL'),
    ('DATABASE_MIGRATED', 'system', 'Base de datos actualizada a una nueva versión', 'WARNING'),
    ('SERVER_STARTED', 'system', 'Servidor iniciado', 'INFO'),
    ('UPDATE_APPLIED', 'system', 'Actualización instalada', 'INFO'),
    ('UPDATE_DOWNLOADED', 'system', 'Actualización descargada y verificada', 'INFO'),
    ('UPDATE_FAILED', 'system', 'Actualización fallida', 'CRITICAL'),
    ('UPDATE_INSTALL_REQUESTED', 'system', 'Instalación inmediata de una actualización solicitada', 'WARNING'),
    ('UPDATE_ROLLED_BACK', 'system', 'Actualización revertida a la versión anterior', 'CRITICAL')
ON CONFLICT (code) DO UPDATE SET module = EXCLUDED.module, name = EXCLUDED.name, default_severity = EXCLUDED.default_severity;
