-- =====================================================================================================
-- R__identity__permissions_catalog · Catálogo de permisos (repetible).
-- FUENTE DE VERDAD: las clases *Permissions del código de cada módulo. La prueba
-- El_catalogo_de_permisos_del_codigo_coincide_con_el_de_la_BD falla si este archivo y el código difieren.
-- Los permisos nunca se borran: los que desaparecen del código se marcan is_deprecated.
-- =====================================================================================================

INSERT INTO identity.permissions (code, module, description, is_sensitive) VALUES
    ('audit.log.verify',              'audit',        'Verificar la integridad de la bitácora de auditoría',                           true),
    ('audit.incident.acknowledge',        'audit',        'Reconocer un incidente de integridad de la bitácora (solo el propietario)',       true),
    ('audit.log.view',                'audit',        'Consultar la bitácora de auditoría',                                            true),
    ('backup.backup.run',                 'backup',       'Respaldar ahora y verificar un backup',                                           false),
    ('backup.backup.view',                'backup',       'Ver el historial de backups, los destinos y las alertas; descargar un backup',    false),
    ('backup.destination.configure',      'backup',       'Configurar los destinos de los backups (carpetas, disco externo, red, nube)',     true),
    ('backup.recovery.manage',            'backup',       'Generar y confirmar el código de recuperación de los backups (solo el propietario)', true),
    ('cash.drawer.open',              'cash',         'Abrir el cajón sin venta (admite autorización de supervisor)',                  true),
    ('cash.movement.withdraw',        'cash',         'Retirar efectivo de la caja (admite autorización de supervisor)',               true),
    ('cash.payment_method.manage',    'cash',         'Crear y modificar medios de pago',                                              true),
    ('cash.report.view',              'cash',         'Ver reportes X y Z de cualquier caja y el esperado antes del arqueo',           true),
    ('cash.session.close_any',        'cash',         'Cerrar la jornada de otro cajero (cierre por supervisor)',                      true),
    ('cash.session.operate',          'cash',         'Abrir y cerrar la propia jornada, registrar ingresos y gastos menores',         false),
    ('cash.session.review',           'cash',         'Revisar cierres con diferencia y registrar correcciones de caja',               true),
    ('catalog.import.run',            'catalog',      'Importar productos y precios desde archivos',                                   true),
    ('catalog.master.manage',         'catalog',      'Categorías, marcas, listas de precios y reglas de báscula',                     false),
    ('catalog.price.manage',          'catalog',      'Fijar, programar y cancelar precios de venta',                                  true),
    ('catalog.product.manage',        'catalog',      'Crear y modificar productos, presentaciones, códigos e impuestos del producto', false),
    ('catalog.product.view',          'catalog',      'Consultar productos, códigos y precios vigentes',                               false),
    ('catalog.tax.manage',            'catalog',      'Crear impuestos y cambiar sus tarifas',                                         true),
    ('expenses.expense.manage',       'expenses',     'Registrar y anular gastos y sus categorías',                                    true),
    ('expenses.expense.view',         'expenses',     'Consultar gastos',                                                              false),
    ('identity.permission.view',      'identity',     'Consultar el catálogo de permisos y los roles',                                 false),
    ('identity.role.manage',          'identity',     'Crear, clonar y editar roles; asignar roles y excepciones',                     true),
    ('identity.session.revoke',       'identity',     'Cerrar sesiones de otros usuarios',                                             true),
    ('identity.user.manage',          'identity',     'Crear, editar, activar y desactivar usuarios; restablecer contraseña o PIN',    true),
    ('identity.user.view',            'identity',     'Consultar usuarios',                                                            false),
    ('inventory.adjustment.approve',  'inventory',    'Aprobar ajustes que superan el umbral',                                         true),
    ('inventory.adjustment.manage',   'inventory',    'Crear ajustes de inventario y saldos iniciales',                                true),
    ('inventory.cost.view',           'inventory',    'Ver costos, valor del inventario y kardex valorizado',                          true),
    ('inventory.count.approve',       'inventory',    'Aprobar un conteo físico (genera los ajustes)',                                 true),
    ('inventory.count.manage',        'inventory',    'Crear, iniciar, revisar y cerrar conteos físicos',                              false),
    ('inventory.count.register',      'inventory',    'Registrar cantidades contadas',                                                 false),
    ('inventory.stock.verify',        'inventory',    'Verificar y reconstruir saldos contra el kardex',                               true),
    ('inventory.stock.view',          'inventory',    'Consultar existencias por bodega (sin costos)',                                 false),
    ('inventory.transfer.manage',     'inventory',    'Crear, despachar y recibir traslados entre bodegas',                            false),
    ('organization.branch.manage',    'organization', 'Crear, modificar e inactivar sucursales',                                       true),
    ('organization.branch.view',      'organization', 'Consultar sucursales, bodegas y cajas',                                         false),
    ('organization.company.manage',   'organization', 'Modificar los datos de la empresa',                                             true),
    ('organization.company.view',     'organization', 'Consultar los datos de la empresa',                                             false),
    ('organization.device.manage',    'organization', 'Generar códigos de emparejamiento y revocar equipos',                           true),
    ('organization.terminal.manage',  'organization', 'Crear, modificar e inactivar cajas',                                            true),
    ('organization.warehouse.manage', 'organization', 'Crear, modificar e inactivar bodegas',                                          true),
    ('parties.party.manage',          'parties',      'Crear y modificar terceros y sus contactos',                                    false),
    ('parties.party.view',            'parties',      'Consultar terceros (proveedores y clientes)',                                   false),
    ('purchasing.order.approve',      'purchasing',   'Aprobar órdenes de compra',                                                     true),
    ('purchasing.order.manage',       'purchasing',   'Crear, enviar y cerrar órdenes de compra',                                      false),
    ('purchasing.payable.pay',        'purchasing',   'Registrar y anular pagos a proveedores',                                        true),
    ('purchasing.payable.view',       'purchasing',   'Consultar cuentas por pagar, pagos y cartera por edades',                       true),
    ('purchasing.purchase.manage',    'purchasing',   'Registrar compras en borrador (factura, líneas, lotes, cargos y retenciones)',  false),
    ('purchasing.purchase.post',      'purchasing',   'Contabilizar compras (entran al inventario y a la cartera)',                    true),
    ('purchasing.purchase.view',      'purchasing',   'Consultar proveedores, órdenes, compras y devoluciones',                        false),
    ('purchasing.purchase.void',      'purchasing',   'Anular compras contabilizadas',                                                 true),
    ('purchasing.return.manage',      'purchasing',   'Registrar, contabilizar y liquidar devoluciones a proveedor',                   true),
    ('purchasing.supplier.manage',    'purchasing',   'Crear y modificar proveedores y los productos que suministran',                 false),
    ('purchasing.supplier.bank_manage', 'purchasing', 'Registrar, modificar y verificar cuentas bancarias de proveedores (admite autorización de supervisor)', true),
    ('billing.document.manage',       'billing',      'Reintentar el envío de documentos electrónicos',                                  true),
    ('billing.document.view',         'billing',      'Consultar comprobantes y documentos fiscales con sus eventos',                    false),
    ('inventory.adjustment.quick',    'inventory',    'Ajuste rápido de un producto desde la caja cuando el sistema no tiene existencias (admite autorización de supervisor)', true),
    ('promotions.promotion.manage',   'promotions',   'Crear, simular, activar, pausar y terminar promociones',                          true),
    ('promotions.promotion.view',     'promotions',   'Consultar promociones y su reporte de descuentos',                                false),
    ('sales.discount.apply',          'sales',        'Aplicar descuentos manuales de línea o globales (admite autorización de supervisor)', true),
    ('sales.exchange.create',         'sales',        'Recibir un cambio de mercancía (admite autorización de supervisor)',              true),
    ('sales.expired.sell',            'sales',        'Vender un producto con existencias de un lote vencido (admite autorización de supervisor)', true),
    ('sales.line.void',               'sales',        'Eliminar una línea de la venta en curso (queda registrada)',                      false),
    ('sales.price.override',          'sales',        'Fijar el precio de un producto con precio abierto (admite autorización de supervisor)', true),
    ('sales.refund.warranty',         'sales',        'Reintegrar dinero por garantía (excepción legal, solo el propietario)',           true),
    ('sales.sale.cancel',             'sales',        'Cancelar una venta en curso o suspendida (admite autorización de supervisor)',    true),
    ('sales.sale.create',             'sales',        'Vender: iniciar, escanear, suspender, recuperar y cobrar',                        false),
    ('sales.sale.reprint',            'sales',        'Reimprimir el tiquete de una venta (marcado COPIA)',                              false),
    ('sales.sale.view',               'sales',        'Consultar ventas, cambios y reportes de ventas',                                  false),
    ('sales.sale.void',               'sales',        'Anular una venta completada con su jornada abierta (admite autorización de supervisor)', true),
    ('customers.customer.manage',         'customers',    'Corregir los datos de un cliente y bloquearlo',                                   false),
    ('customers.customer.quick_create',   'customers',    'Crear clientes desde la caja, completar datos vacíos y registrar su autorización de datos', false),
    ('customers.customer.view',           'customers',    'Buscar clientes y ver su ficha básica',                                           false),
    ('customers.group.manage',            'customers',    'Crear y modificar grupos de clientes',                                            false),
    ('customers.history.view',            'customers',    'Ver el historial y el resumen de compras de un cliente',                          false),
    ('customers.pricing.assign',          'customers',    'Asignar el grupo y la lista de precio de un cliente',                             true),
    ('customers.privacy.manage',          'customers',    'Política de datos, solicitudes de titulares, exportación y supresión de datos',   true),
    ('reporting.antifraud.view',          'reporting',    'Ver el panel antifraude por cajero y el detalle de sus eventos',                  true),
    ('reporting.cash.view',               'reporting',    'Ver reportes de cierres, retiros e ingresos de caja',                             false),
    ('reporting.report.export',           'reporting',    'Exportar reportes a Excel, CSV o PDF (queda en la auditoría)',                    true),
    ('reporting.inventory.view',          'reporting',    'Ver reportes de inventario: valorizado, bajo mínimo, sin rotación, vencimientos y ajustes', false),
    ('reporting.profit.view',             'reporting',    'Ver utilidad, costos y márgenes de las ventas',                                   true),
    ('reporting.purchases.view',          'reporting',    'Ver reportes de compras, devoluciones, cartera por pagar y gastos',               false),
    ('reporting.sales.advanced',          'reporting',    'Ver ventas por producto, categoría, marca, cliente, lista, descuentos y promociones', false),
    ('reporting.sales.basic',             'reporting',    'Ver ventas por día, hora, medio de pago, cajero y caja, y el tablero del día',     false),
    ('reporting.taxes.view',              'reporting',    'Ver impuestos de ventas y compras y el libro de ventas diario',                   false),
    ('settings.setting.manage',       'settings',     'Modificar la configuración general',                                            true),
    ('settings.setting.view',         'settings',     'Consultar la configuración general',                                            false)
ON CONFLICT (code) DO UPDATE SET module = EXCLUDED.module, description = EXCLUDED.description,
    is_sensitive = EXCLUDED.is_sensitive, is_deprecated = false;

-- Los permisos que ya no están en el código quedan obsoletos (no se borran).
UPDATE identity.permissions SET is_deprecated = true
WHERE code NOT IN (
    'audit.incident.acknowledge', 'audit.log.verify', 'audit.log.view', 'backup.backup.run', 'backup.backup.view', 'backup.destination.configure', 'backup.recovery.manage', 'catalog.import.run', 'catalog.master.manage', 'catalog.price.manage',
    'catalog.product.manage', 'catalog.product.view', 'catalog.tax.manage', 'identity.permission.view',
    'identity.role.manage', 'identity.session.revoke', 'identity.user.manage', 'identity.user.view',
    'inventory.adjustment.approve', 'inventory.adjustment.manage', 'inventory.cost.view', 'inventory.count.approve',
    'inventory.count.manage', 'inventory.count.register', 'inventory.stock.verify', 'inventory.stock.view',
    'inventory.transfer.manage', 'organization.branch.manage', 'organization.branch.view',
    'organization.company.manage', 'organization.company.view', 'organization.device.manage',
    'organization.terminal.manage', 'organization.warehouse.manage', 'settings.setting.manage',
    'settings.setting.view', 'cash.payment_method.manage', 'parties.party.manage', 'parties.party.view',
    'purchasing.order.approve', 'purchasing.order.manage', 'purchasing.payable.pay', 'purchasing.payable.view',
    'purchasing.purchase.manage', 'purchasing.purchase.post', 'purchasing.purchase.view', 'purchasing.purchase.void',
    'purchasing.return.manage', 'purchasing.supplier.manage', 'purchasing.supplier.bank_manage', 'cash.drawer.open', 'cash.movement.withdraw', 'cash.report.view',
    'cash.session.close_any', 'cash.session.operate', 'cash.session.review', 'expenses.expense.manage', 'expenses.expense.view',
    'billing.document.manage', 'billing.document.view', 'inventory.adjustment.quick', 'promotions.promotion.manage', 'promotions.promotion.view', 'sales.discount.apply', 'sales.exchange.create', 'sales.expired.sell', 'sales.line.void', 'sales.price.override', 'sales.refund.warranty', 'sales.sale.cancel', 'sales.sale.create', 'sales.sale.reprint', 'sales.sale.view', 'sales.sale.void',
    'customers.customer.manage', 'customers.customer.quick_create', 'customers.customer.view', 'customers.group.manage', 'customers.history.view', 'customers.pricing.assign', 'customers.privacy.manage',
    'reporting.antifraud.view', 'reporting.cash.view', 'reporting.report.export', 'reporting.inventory.view', 'reporting.profit.view',
    'reporting.purchases.view', 'reporting.sales.advanced', 'reporting.sales.basic', 'reporting.taxes.view');
