<Project Sdk="Microsoft.NET.Sdk">
  <!-- Módulo Reference · Casos de uso (comandos y consultas) y puertos de persistencia. -->
  <PropertyGroup>
    <RootNamespace>Pos.Modules.Reference.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Pos.Application.Abstractions/Pos.Application.Abstractions.csproj" />
    <ProjectReference Include="../Pos.Modules.Reference.Contracts/Pos.Modules.Reference.Contracts.csproj" />
  </ItemGroup>
</Project>
