-- =====================================================================================================
-- V2026.10.002 · audit · Bitácora de la NUBE: misma estructura que la del POS (V2026.10.005 del POS) para reutilizar el
-- formato de hash, el sellador por lotes y el verificador (ADR-0012). company_id/branch_id/pos_terminal_id quedan nulos;
-- user_id es el usuario del portal; device_id no se usa. Solo inserción (privilegios + disparadores).
-- =====================================================================================================

CREATE TABLE audit.audit_log (
    id                 uuid          NOT NULL,
    occurred_at        timestamptz   NOT NULL,
    node_id            uuid          NOT NULL,
    seq                bigint        GENERATED BY DEFAULT AS IDENTITY,
    hash_version       smallint      NOT NULL,
    company_id         uuid,
    branch_id          uuid,
    pos_terminal_id    uuid,
    user_id            uuid,
    user_display_name  varchar(120),
    session_id         uuid,
    device_id          uuid,
    ip_address         inet,
    correlation_id     varchar(64),
    module             varchar(30)   NOT NULL,
    action             varchar(60)   NOT NULL,
    entity_type        varchar(60),
    entity_id          uuid,
    entity_label       varchar(200),
    old_values         jsonb,
    new_values         jsonb,
    summary            varchar(500),
    authorized_by      uuid,
    severity           varchar(10)   NOT NULL,
    row_hash           char(64)      NOT NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (occurred_at, id),
    CONSTRAINT ck_audit_log__action CHECK (action ~ '^[A-Z][A-Z0-9_]+$'),
    CONSTRAINT ck_audit_log__severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT ck_audit_log__hash_version CHECK (hash_version > 0),
    CONSTRAINT ck_audit_log__row_hash CHECK (row_hash ~ '^[0-9a-f]{64}$')
) PARTITION BY RANGE (occurred_at);

CREATE INDEX ix_audit_log__entity ON audit.audit_log (entity_type, entity_id, occurred_at);
CREATE INDEX ix_audit_log__user ON audit.audit_log (user_id, occurred_at);
CREATE INDEX ix_audit_log__module_action ON audit.audit_log (module, action, occurred_at);
-- PostgreSQL exige la clave de partición en los índices únicos: la unicidad de (node_id, seq) la garantizan
-- la secuencia y el verificador.
CREATE INDEX ix_audit_log__node_seq ON audit.audit_log (node_id, seq, occurred_at);

-- Garantiza que una inserción nunca falle por falta de partición.
CREATE TABLE audit.audit_log_default PARTITION OF audit.audit_log DEFAULT;

-- Crea las particiones mensuales (UTC) desde el mes actual hasta months_ahead meses después.
-- SECURITY DEFINER: pos_app no tiene DDL; el mantenimiento diario la invoca.
-- Si la partición DEFAULT ya tiene filas de ese mes, no se crea (quedan en DEFAULT) y se informa.
CREATE FUNCTION audit.ensure_partitions(months_ahead integer DEFAULT 3) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, audit AS $$
DECLARE
    v_start   timestamptz;
    v_end     timestamptz;
    v_name    text;
    v_created integer := 0;
BEGIN
    IF months_ahead < 0 OR months_ahead > 24 THEN
        RAISE EXCEPTION 'months_ahead fuera de rango: %', months_ahead;
    END IF;

    FOR i IN 0..months_ahead LOOP
        v_start := date_trunc('month', now() AT TIME ZONE 'UTC') AT TIME ZONE 'UTC' + make_interval(months => i);
        v_end   := v_start + interval '1 month';
        v_name  := 'audit_log_' || to_char(v_start AT TIME ZONE 'UTC', 'YYYY_MM');

        CONTINUE WHEN EXISTS (
            SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'audit' AND c.relname = v_name);

        IF EXISTS (SELECT 1 FROM audit.audit_log_default WHERE occurred_at >= v_start AND occurred_at < v_end) THEN
            RAISE NOTICE 'La partición DEFAULT ya contiene filas de %, no se crea %', v_start, v_name;
            CONTINUE;
        END IF;

        EXECUTE format('CREATE TABLE audit.%I PARTITION OF audit.audit_log FOR VALUES FROM (%L) TO (%L)',
                       v_name, v_start, v_end);
        v_created := v_created + 1;
    END LOOP;

    RETURN v_created;
END;
$$;

REVOKE ALL ON FUNCTION audit.ensure_partitions(integer) FROM PUBLIC;

SELECT audit.ensure_partitions(3);

-- -----------------------------------------------------------------------------------------------------
-- Sellos: una cadena por nodo. seal_hash = SHA-256 del JCS {v, node_id, seal_no, seq_from, seq_to,
-- rows_count, rows_digest, prev_seal_hash, sealed_at}.
-- -----------------------------------------------------------------------------------------------------
CREATE TABLE audit.audit_seals (
    id              bigint        GENERATED ALWAYS AS IDENTITY,
    node_id         uuid          NOT NULL,
    seal_no         bigint        NOT NULL,
    format_version  smallint      NOT NULL,
    seq_from        bigint        NOT NULL,
    seq_to          bigint        NOT NULL,
    rows_count      integer       NOT NULL,
    rows_digest     char(64)      NOT NULL,
    prev_seal_hash  char(64)      NOT NULL,
    seal_hash       char(64)      NOT NULL,
    sealed_at       timestamptz   NOT NULL,
    CONSTRAINT pk_audit_seals PRIMARY KEY (id),
    CONSTRAINT ux_audit_seals__node_seal_no UNIQUE (node_id, seal_no),
    CONSTRAINT ux_audit_seals__seal_hash UNIQUE (seal_hash),
    CONSTRAINT ck_audit_seals__seal_no CHECK (seal_no > 0),
    CONSTRAINT ck_audit_seals__range CHECK (seq_from > 0 AND seq_to >= seq_from),
    CONSTRAINT ck_audit_seals__rows_count CHECK (rows_count >= 0 AND rows_count <= seq_to - seq_from + 1),
    CONSTRAINT ck_audit_seals__hashes CHECK (
        rows_digest ~ '^[0-9a-f]{64}$' AND prev_seal_hash ~ '^[0-9a-f]{64}$' AND seal_hash ~ '^[0-9a-f]{64}$')
);

-- -----------------------------------------------------------------------------------------------------
-- Append-only: UPDATE/DELETE/TRUNCATE lanzan error incluso para roles con privilegios (defensa adicional
-- a los privilegios: pos_app solo tiene SELECT/INSERT).
-- -----------------------------------------------------------------------------------------------------
CREATE FUNCTION audit.fn_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'La tabla %.% es de solo inserción', TG_TABLE_SCHEMA, TG_TABLE_NAME
        USING ERRCODE = '42501';
END;
$$;

CREATE TRIGGER trg_audit_log_append_only
    BEFORE UPDATE OR DELETE ON audit.audit_log
    FOR EACH ROW EXECUTE FUNCTION audit.fn_append_only();

CREATE TRIGGER trg_audit_seals_append_only
    BEFORE UPDATE OR DELETE ON audit.audit_seals
    FOR EACH ROW EXECUTE FUNCTION audit.fn_append_only();

CREATE TRIGGER trg_audit_seals_no_truncate
    BEFORE TRUNCATE ON audit.audit_seals
    FOR EACH STATEMENT EXECUTE FUNCTION audit.fn_append_only();
