<Project Sdk="Microsoft.NET.Sdk">
  <!-- Módulo Organization · Dominio puro: entidades, reglas e invariantes. Solo depende del SharedKernel. -->
  <PropertyGroup>
    <RootNamespace>Pos.Modules.Organization.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Pos.SharedKernel/Pos.SharedKernel.csproj" />
  </ItemGroup>
</Project>
